### PR TITLE
Update 01_init.sh

### PR DESCRIPTION
**Pull request by hermannschwaerzlerUIBK**
Brace Expansion supports "0-padded" numbers, which make this a bit easier.
But you might want to keep it for "educational purposes"? :-)

### CODE REVIEW

**Comment by jperkel** [comment]
But for 0-9, the result isn't zero-padded? 

```
$ for i in {01..10}; do echo "$i"; done
1
2
3
4
5
6
7
8
9
10
```

**Comment by hermannschwaerzlerUIBK** [comment]
Oh, sorry, I see this seems to depend on some settings or the version of bash. This ist the output for me:
```
for i in {01..10}; do echo "$i"; done
01
02
03
04
05
06
07
08
09
10

bash --version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

BTW: the `Brace Expansion` section of *my* bash's man-page contains this:
```
 A sequence expression takes the form {x..y[..incr]} [...]. 
 When either x or y begins with a zero, the shell attempts to force all 
 generated terms to contain the same number of digits, zero-padding 
 where necessary.
```
Which version of bash are you using?
What does your bash's man-page say wrt this?

**Comment by jperkel** [comment]
Ah! I have the version that ships with macOS:
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by hermannschwaerzlerUIBK** [comment]
Looks like this behaviour changed from version 3 to version 4 of bash as on another system with bash version 4.1.2 the zero-padding works.
In that case I think you should close my pull-request without accepting it. :-)

**Comment by jperkel** [comment]
Thanks for the suggestion, @hermannschwaerzlerUIBK !

**Pull request closed without merging**
